name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.6.7']

    steps:
    - uses: actions/checkout@v4

    - name: Install Protocol Buffers compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'

    - name: Cache cabal packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          haskell/dist-newstyle
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('**/serializotron.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-

    - name: Update cabal package database
      working-directory: haskell
      run: cabal update

    - name: Install proto-lens-protoc
      run: cabal install proto-lens-protoc --install-method=copy --overwrite-policy=always

    - name: Build dependencies
      working-directory: haskell
      run: cabal build --only-dependencies --enable-tests

    - name: Build
      working-directory: haskell
      run: cabal build --enable-tests

    - name: Run tests
      working-directory: haskell
      run: cabal test --test-show-details=direct
